### ISSUE TITLE
Display block proposer on block page

### ISSUE THREAD

**Issue by nullun** [algorandfoundation/algokit-lora#157]
With incentives coming out there's going to be more interest in who the block proposer is. Having it displayed in the top box on the block page would be ideal.
<img width="577" alt="Screenshot 2024-07-17 at 10 26 27" src="https://github.com/user-attachments/assets/d69fca17-a6c1-4282-8fd4-33ead99d3694">
I'm not sure if it's worth including on the latest blocks page? I don't think it's _that_ important.
<img width="646" alt="Screenshot 2024-07-17 at 10 29 49" src="https://github.com/user-attachments/assets/6d56d01c-257a-488b-a87b-2cdb666406fa">

**Comment by nullun** [comment]
I just realised in the future version of algod, the proposer is easily found in the block header as `prp`. Whereas right now you'd need to retrieve the msgpack version of the block and check the cert. So rather than changing this code twice, maybe you just want to target the future algod release which has a slightly different json response.
<img width="586" alt="Screenshot 2024-07-17 at 14 08 55" src="https://github.com/user-attachments/assets/6578265e-87d2-4fee-bf72-14f5644f3399">

**Comment by neilcampbell** [comment]
Nice! Do you know if this will also be added to the indexer response?

**Comment by nullun** [comment]
The indexer should definitely be updated with these fields too. I found a fork with some updates, but nothing merged/PRed to the official repo yet. I imagine it would be somehting similar to the below screenshot.
<img width="632" alt="Screenshot 2024-07-23 at 15 22 09" src="https://github.com/user-attachments/assets/b92a051b-c37e-47ec-90d6-90b9064f21f5">
