### ISSUE TITLE
Support network changes in here

### ISSUE THREAD

**Issue by josecao** [algorandfoundation/algokit-lora#160]
Hi team,

Can you change text to select component for this ?

<img width="271" alt="Screenshot 2024-07-23 at 12 55 38" src="https://github.com/user-attachments/assets/5ec24cb8-8e0c-411d-a1d8-bcc642fe8754">

**Comment by neilcampbell** [comment]
You can click that text, and it'll take you to the network selection.
We initially had it like that, however moved to settings, as it's a weird experience to be viewing a transaction, switch network and see a error (404). We also didn't like navigating elsewhere (to prevent the 404) as part of selecting a network.
