### ISSUE TITLE
Back Btn is not working when change active network

### ISSUE THREAD

**Issue by josecao** [algorandfoundation/algokit-lora#166]
https://drive.google.com/file/d/1TPhEW1LX1VtVD6M69cnKjV2GxmpUQNVu/view?usp=sharing

**Comment by neilcampbell** [comment]
In that example, would you expect your active network to change back to mainnet and that transaction be displayed?

**Comment by josecao** [comment]
Sorry but I'm not sure, but I think we should stay on testnet and redirect to explore page

**Comment by neilcampbell** [comment]
Cool, I was thinking something similar. I'll see what I can do.

**Comment by neilcampbell** [comment]
@josecao We've changed the behaviour to match what we spoke about above.

**Comment by josecao** [comment]
@neilcampbell, thank you!
