### ISSUE TITLE
[local-dev-experience-ui] Format ABI method information

### ISSUE THREAD

**Issue by PatrickDinh** [algorandfoundation/algokit-lora#187]
## Description

- When viewing a transaction of an application which has an arc4/arc32/arc56 app spec, the app call method, arguments and return value are formatted with prettier (or something similar) to make it shorter and are syntax highlighted similar to the JSON view to make easier to read.

## Acceptance Criteria

1. When viewing a transaction of an application which has an arc32 app spec, the app call method, arguments and return value are prettified and syntax highlighted.
1. When viewing a transaction of an application which has an arc4 app spec, the app call method, arguments and return value are prettified and syntax highlighted.
1. When viewing a transaction of an application which has an arc56 app spec, the app call method, arguments and return value are prettified and syntax highlighted.

**Comment by neilcampbell** [comment]
We might be able to use this package https://www.npmjs.com/package/js-beautify
