### ISSUE TITLE
[local-dev-experience] Users can create and deploy an app in the app studio

### ISSUE THREAD

**Issue by neilcampbell** [algorandfoundation/algokit-lora#206]
## Description

As an AlgoKit user
I want to create and deploy an app in the app studio
So that I can deploy and then visually interact with my app

## Technical Details

- Upload app spec (we only support ABI)
- Choose a name (prefill with name from the app spec)
- Deploy the app and resolve the app id
- Applications are contextual to network, and user can have different applications across networks

## Questions

- Should an app be created as mutable or immutable?

## Acceptance Criteria

- A user can create and deploy an app in the app studio.
- Applications are only created against the current network that user is connected to.
- User will be prompted to choose a different name if they enter an app name which has already been used for that network.

**Comment by PatrickDinh** [comment]
@neilcampbell I think we need to update the AC 
"User will be prompted to choose a different name if they enter an app name which has already been used for that network."
We are using algokit-utils for deployment, therefore, updating an existing app is possible.

**Comment by neilcampbell** [comment]
@PatrickDinh All these stories were created prior to choosing App interface, over App. This is referring to the app interface name.
