### ISSUE TITLE
Incorrect display of large numbers in app global state

### ISSUE THREAD

**Issue by uhudo** [algorandfoundation/algokit-lora#365]
Issue: Lora incorrectly displays the last digits of large numbers in the global state of applications, e.g. `33399922244455501` is displayed as `33399922244455500`
It seems to be rounding them.

**Comment by neilcampbell** [comment]
Thanks for reporting @uhudo. Do you have an app id on mainnet or testnet we can inspect?

**Comment by uhudo** [comment]
Unfortunately not. I've just noticed it while doing tests on localnet.

**Comment by neilcampbell** [comment]
No problems, should be pretty easy to reproduce.

**Comment by PatrickDinh** [comment]
hi @uhudo, I have fixed this issue in #366, can you please confirm if it's fixed in your localnet?

**Comment by uhudo** [comment]
Yes, it's correct now.
Thanks for the quick fix!
